ab teh the
ab Accesoir Accesoire
ab Acksessoir Accesoire
ab adequat adäquat
ab adnere andere
ab adneren anderen
ab adneres anderes
ab adners anders
ab angand anhand
ab Amalgan Amalgam
ab änlich ähnlich
ab Apperat Apparat
ab Apperatur Apparatur
ab Aquisition Akquisition
ab arbiete arbeite
ab arbieten arbeiten
ab arbietest arbeitest
ab arbietet arbeitet
ab Argumnet Argument
ab Artz Arzt
ab Assessoir Accessoire
ab Auswal Auswahl
ab awr war
ab beerits bereits
ab bekant bekannt
ab bescäftigt beschäftigt
ab Bekante Bekannte
ab Bekanter Bekannter
ab bekantes bekanntes
ab Belästignug Belästigung
ab bereis bereits
ab beries bereits
ab beriets bereits
ab Beispeilsweise Beispielsweise
ab Bibliotehk Bibliothek
ab Bibliotekh Bibliothek
ab Bibliothrk Bibliothek
ab Buchsabe Buchstabe
ab Buchstbae Buchstabe
ab cielleicht vielleicht
ab cm2 cm^2
ab cm3 cm^3
ab dachet dachte
ab dähmlich dämlich
ab daselbe dasselbe
ab Datein Dateien
ab dei die
ab deis dies
ab dekne denke
ab dise dies
ab Dnak Dank
ab dnake danke
ab Dockument Dokument
ab dre der
ab dsa das
ab dßa daß
ab edr der
ab emfehlen empfehlen
ab enldich endlich
ab Entgeld Entgelt
ab Entwicklug Entwicklung
ab Entwicklugn Entwicklung
ab Enwicklung Entwicklung
ab ereiche erreiche
ab ereichen erreichen
ab ereichst erreichst
ab ereicht erreicht
ab Erflg Erfolg
ab Erflog Erfolg
ab erhlate erhalte
ab erhlaten erhalten
ab erinern erinnern
ab errinern erinnern
ab errinnern erinnern
ab erts erst
ab fandn fanden
ab Faru Frau
ab findn finden
ab Firna Firma
ab fnaden fanden
ab Fnester Fenster
ab follgende folgende
ab Fra Frau
ab Fraeg Frage
ab fragn fragen
ab Freudne Freunde
ab Freudnin Freundin
ab Freundinen Freundinnen
ab Frima Firma
ab Fru Frau
ab fsat fast
ab Garanti Garantie
ab Garranti Garantie
ab Garrantie Garantie
ab Gechichte Geschichte
ab gehn gehen
ab Geidcht Gedicht
ab Geschichtne Geschichten
ab geselschaftlichen gesellschaftlichen
ab Geshichte Geschichte
ab gnaz ganz
ab Grupe Gruppe
ab Gruss Gruß
ab Grüsse Grüße
ab habn haben
ab hbe habe
ab hbae habe
ab heiss heiß
ab hielig heilig
ab huete heute
ab Hypotehk Hypothek
ab Hypotek Hypothek
ab ien ein
ab ienige einige
ab Ieroni Ironie
ab Ieronie Ironie
ab ieronisch ironisch
ab ihc ich
ab Intregation Integration
ab intregrieren integrieren
ab Intriege Intrige
ab intriegieren intrigieren
ab ires ihres
ab Ironi Ironie
ab iwer irgendwer
ab iwie irgendwie
ab iwo irgendwo
ab Jare Jahre
ab jettz jetzt
ab jezt jetzt
ab Kartein Karteien
ab kien kein
ab kiene keine
ab kienes keines 
ab kiense keines 
ab klra klar 
ab km2 km² 
ab knan kann 
ab kannn kann
ab Komite Komitee
ab Kommite Komitee
ab Kommitee Komitee
ab Kommittee Komitee
ab Komunikation Kommunikation
ab komunizieren kommunizieren
ab könte könnte
ab Kopei Kopie
ab korregieren korrigieren
ab korregierst korrigierst
ab korregiert korrigiert
ab Kres Kreis
ab Kries Kreis
ab lebn leben
ab Leistnug Leistung
ab Lizens Lizenz
ab Lizensierung Lizenzierung
ab Lizentz Lizenz
ab Lizentzierung Lizenzierung
ab Luete Leute
ab m2 m²
ab m3 m³
ab machn machen
ab macen machen
ab Menscen Menschen
ab mfg Mit freundlichen Grüßen
ab mm2 mm²
ab mm3 mm³
ab mna man
ab mti mit
ab nähmlich nämlich
ab nciht nicht
ab Nunner Nummer
ab ofenbar offenbar
ab paralell parallel
ab Partein Parteien
ab Piknick Picknick
ab Piknik Picknick
ab Porblem Problem
ab Porzelan Porzellan
ab Rechnnug Rechnung
ab Rechnug Rechnung
ab Reperatur Reparatur
ab Rhytmus Rhythmus
ab Rythmus Rhythmus
ab Rytmus Rhythmus
ab Sahce Sache
ab selig seelig
ab seperat separat
ab serh sehr
ab sgdh Sehr geehrte Damen Herren
ab sien sein
ab sich sich
ab Sone Sonne
ab Standart Standard
ab Stenr Stern
ab steen stehen
ab sthest stehst
ab sthet steht
ab Stien Stein
ab Stren Stern
ab Tribühne Tribüne
ab uas aus
ab udn und
ab umbedingt unbedingt
ab umzufrieden unzufrieden
ab unentgeldlich unentgeltlich
ab veilleicht vielleicht
ab veilliecht vielleicht
ab Verat Verrat
ab verberitetes verbreitetes
ab vieleicht vielleicht
ab Vokl Volk
ab Vokla Vokal
ab Voklae Vokale
ab Vorang Vorrang
ab Vorat Vorrat
ab währendt während
ab wärend während
ab wedre werde
ab weiseb weisen
ab Widergabe Wiedergabe
ab widergeben wiedergeben
ab wiederspiegeln widerspiegeln
ab Wrot Wort
ab wwar war
ab wüdre würde
ab Zeti Zeit
ab Zite Zeit
ab math_and ∧
ab math_or ∨
ab math_inf ∞
ab math_triangle △
ab math_elem ∈
ab math_not_contain ∌
ab math_contain ∋
ab math_integral
ab ∫ music_gclef
ab 𝄞 music_1
ab music_12 𝅗𝅥
ab music_14 ♩
ab music_18 ♪
ab music 116 𝅘𝅥𝅯
ab music_b ♭
ab music_# ♯
ab greek_alpha α
ab greek_Alpha Α
ab greek_beta β
ab greek_Beta Β
ab greek_gamma γ
ab greek_Gamma Γ
ab greek_delta δ
ab greek_Delta Δ
ab greek_epsilon ε
ab greek_Epsilon Ε
ab greek_Zeta Ζ
ab greek_zeta ζ
ab greek_eta η
ab greek_Eta Η
ab greek_Theta Θ
ab greek_theta θ
ab greek_Iota Ι
ab greek_iota ι
ab greek_Kappa Κ
ab greek_kappa κ
ab greek_Lambda Λ
ab greek_lambda λ
ab greek_Mu Μ
ab greek_mu μ
ab greek_nu Ν
ab greek_nu ν
ab greek_Xi Ξ
ab greek_xi ξ
ab greek_Omicron Ο
ab greek_omikron ο
ab greek_Pi Π
ab greek_pi π
ab greek_Rho Ρ
ab greek_rhp ρ
ab greek_Sigma Σ
ab greek_sigma σ
ab greek_sigma2 ς
ab greek_Tau Τ
ab greek_tau τ
ab greek_Y Υ
ab greek_y υ
ab greek_Phi Φ
ab greek_phi φ
ab greek_Chi Χ
ab greek_chi χ
ab greek_Pi Ψ
ab greek_psi ψ
ab greek_Omega Ω
ab greek_omega ω
ab sign_record ⏺
ab sign_count1 ◦
ab sign_count2 •
ab sign_count3 ‣
ab sign_lightn 🗲
ab sign_bed 🛏
ab sign_cloudy 🌤
ab sign_eye 👁
ab sign_women 🚺
ab sign_men 🚹
ab sign_thumbs_up 🖒
ab sign_thumbs_down 🖓
ab sign_save 🖫
ab sign_earth 🌍
ab sign_earth_asia 🌏
ab sign_earth_america 🌎
ab sign_factory 🏭
ab sign_family 👪
ab sign_tv 📺
ab sign_grauduated 🎓
ab sign_true ✓
ab sign_warn ⚠
ab sign_money 💰
ab sign_12345 ⛤
ab sign_brush 🖌
ab anim_cat 🐱
ab anim_cow 🐮
ab anim_mouse 🐭
ab anim_fish 🐟
ab currency_bitcoin ₿
ab currency_euro €
ab currency_peso ₱
ab _min ₋
ab _pl ₍
ab _pr ₎
ab _plus ₊
ab _eq ₌
ab __0 ₀
ab __1 ₁
ab __2 ₂
ab __3 ₃
ab __4 ₄
ab __n ₙ
